name: FeliciaCarterTV
favicon: null
layout_spectrum: 0.2989932887721807
typography_spectrum: 0.38833671249449253
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15041531180031598
  lightness: 0.47499403241090477
  saturation: 0.5496440336573869
  rhythmicContrast: 0.6464374735951424
purpose: []
